// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client.Model.Vo;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Model.Vo.Template
{

    public class InverseWordLayer : IImageShape
    {
        private WordLayer _l;

        public InverseWordLayer(WordLayer wordLayer)
        {
            this._l = wordLayer;
        }

        public bool Contains(int x, int y, int width, int height, double rotation, bool transformed)
        {
            return !_l.Contains(x, y, width, height, rotation, transformed);
        }

        public bool ContainsPoint(int x, int y, bool transformed)
        {
            return !_l.containsPo((int)x, y, transformed);
        }

        public virtual bool Intersects(double x, double y, double width, double height, bool transformed)
        {
            return !_l.Intersects(x, y, width, height, transformed);
        }

        public double Width
        {
            get
            {
                return _l.width;
            }
        }

        public double Height
        {
            get
            {
                return _l.height;
            }
        }
    }

}
