// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------

using Com.Settinghead.Wexpression.Client;
using Com.Settinghead.Wexpression.Client.Angler;
using Com.Settinghead.Wexpression.Client.Colorer;
using Com.Settinghead.Wexpression.Client.Density;
using Com.Settinghead.Wexpression.Client.Fonter;
using Com.Settinghead.Wexpression.Client.Model.Vo;
using Com.Settinghead.Wexpression.Client.Nudger;
using Com.Settinghead.Wexpression.Client.Placer;
using Com.Settinghead.Wexpression.Client.Sizers;
using Java.Awt;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Model.Vo.Template
{
    [Bindable]
    public class TemplateVO : IZippable
    {
        private BBPolarRootTreeVO tree;
        private Rectangle _bounds = null;
        private static const double SAMPLE_DISTANCE = 100;
        private static const double MISS_PERCENTAGE_THRESHOLD = 0.1;
        private String _path;
        private WordSizer _sizer;
        private WordFonter _fonter;
        private WordColorer _colorer;
        private WordPlacer _placer;
        private WordNudger _nudger;
        private WordAngler _angler;
        private RenderOptions _renderOptions;
        //		private Array hsbArray;
        private DensityPatchIndex _patchIndex;
        private double _width, _height;
        private ByteArray _previewPNG;
        public int mixColorDistance = 5;
        public int dilligence = 10;

        // Applet applet = new Applet();
        // Frame frame = new Frame("Roseindia.net");
        private ArrayCollection _layers = new ArrayCollection();

        public TemplateVO(String path)
        {
            this._path = path;
        }

        public ArrayCollection layers
        {
            get
            {
                return this._layers;
            }
        }

        public string path
        {
            get
            {
                return _path;
            }
        }

        public double width
        {
            get
            {
                if (isNaN(_width))
                {
                    double maxWidth = 0;
                    foreach (Layer l in layers)
                        if (maxWidth < l.width) maxWidth = l.width;
                    if (maxWidth > 0) _width = maxWidth;
                }
                return _width;
            }
            set
            {
                _width = value;
            }
        }

        public double height
        {
            get
            {
                if (isNaN(_height))
                {
                    double maxHeight = 0;
                    foreach (Layer l in layers)
                        if (maxHeight < l.height) maxHeight = l.height;
                    if (maxHeight > 0) _height = maxHeight;
                }
                return _height;
            }
            set
            {
                _height = value;
            }
        }


        public ByteArray previewPNG
        {
            get
            {
                return _previewPNG;
            }
            set
            {
                _previewPNG = value;
            }
        }

        public DensityPatchIndex patchIndex
        {
            get
            {
                return this._patchIndex;
            }
        }

        public WordPlacer placer
        {
            get
            {
                if (this._placer == null)
                {
                    this._placer = new ShapeConfinedPlacer(this, _patchIndex);
                }
                return this._placer;
            }
        }

        public WordSizer sizer
        {
            get
            {
                if (this._sizer == null)
                {
                    this._sizer = new ByWeightSizer(10, 100);
                }
                return this._sizer;
            }
        }

        public WordFonter fonter
        {
            get
            {
                if (this._fonter == null)
                {
                    this._fonter = new AlwaysUseFonter("Vera");
                }
                return this._fonter;
            }
        }


        public WordColorer colorer
        {
            get
            {
                if (this._colorer == null)
                {
                    this._colorer = new ColorSheetColorer();
                }
                return this._colorer;
            }
        }

        public WordNudger nudger
        {
            get
            {
                if (this._nudger == null)
                {
                    //								this._nudger = new ShapeConfinedSpiralWordNudger();
                    //				this._nudger = new ShapeConfinedRandomWordNudger();
                    this._nudger = new ShapeConfinedZigZagWordNudger();

                }
                return this._nudger;
            }
        }

        public RenderOptions renderOptions
        {
            get
            {
                if (this._renderOptions == null)
                {
                    this._renderOptions = new RenderOptions();
                }
                return this._renderOptions;
            }
        }

        public void onLoadComplete(Event evt0)
        {
            this._patchIndex = new DensityPatchIndex(this);
        }

        public virtual void WriteNonJSONPropertiesToZip(IZipOutput output)
        {
            output.PutBytesToFile("preview.png", previewPNG);
            output.Process(this.layers, "layers");
            output.Process(this.fonter, "fonter");
            output.Process(this.sizer, "sizer");
            output.Process(this.colorer, "colorer");
            //			output.process(this._nudger, "nudger");
            //			output.process(this._angler, "angler");
            //			output.process(this._placer, "placer");
            output.Process(this.renderOptions, "renderOptions");
        }

        public virtual void ReadNonJSONPropertiesFromZip(IZipInput input)
        {

        }

        public virtual void SaveProperties(Object dict)
        {
            dict.path = this._path;
            dict.width = this._width;
            dict.height = this._height;
            dict.dilligence = this.dilligence;
        }

    }
}
