// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client;
using Com.Settinghead.Wexpression.Client.Model;
using Com.Settinghead.Wexpression.Client.Model.Vo;
using Com.Settinghead.Wexpression.Client.Model.Vo.Template;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using PureMVC.Patterns;
using PureMVC.Interfaces;

namespace Com.Settinghead.Wexpression.Client.Controller.Template
{
    public class GenerateTemplatePreviewCommand : SimpleCommand
    {

        private TuProxy tuProxy;

        private IResponder responder;

        public GenerateTemplatePreviewCommand()
        {
            this.tuProxy = Facade.retrieveProxy(TuProxy.NAME) as TuProxy;
        }

        public void execute(INotification note)
        {
            this.responder = note.getBody() as IResponder;
            TemplateVO template = note.getBody() as TemplateVO;
            Assert.notNull(template);
            tuProxy.setData(template);
            WordListProxy wordListProxy = Facade.retrieveProxy(WordListProxy.NAME) as WordListProxy;
            tuProxy.TuGenerated += Result;
            TuVO tu = new TuVO(template, wordListProxy.sampleWordList());
            tuProxy.tu = tu;
            sendNotification(ApplicationFacade.GENERATE_TU);
        }

        private void Result(Object semder, EventArgs e)
        {
            tuProxy.previewGenerationResponder = null;
            responder.Result(data);
        }
    }
}
