// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client;
using Com.Settinghead.Wexpression.Client.Model;
using Com.Settinghead.Wexpression.Client.Model.Business;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using PureMVC.Interfaces;
using PureMVC.Patterns;
namespace Com.Settinghead.Wexpression.Client.Controller.Template
{

    public class LoadTemplateCommand : SimpleCommand, IResponder
    {
        public void execute(INotification note)
        {
            String templateId = note.getBody() as String;
            TemplateDelegate _delegate = new TemplateDelegate(this);
            _delegate.getTemplate(templateId);
        }

        public void Result(Object data)
        {
            facade.RetrieveProxy(TemplateProxy.NAME).SetData(data.result);
            SendNotification(ApplicationFacade.TEMPLATE_LOADED);
        }

        public void Fault(Object info)
        {
            CursorManager.RemoveBusyCursor();
            Alert.Show("Error: " + info.ToString());
        }
    }

}
