// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client;
using Com.Settinghead.Wexpression.Client.Model;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using PureMVC.Interfaces;
using PureMVC.Patterns;
using System.Net;
using Com.Settinghead.Wexpression.Client.Model.Vo.Template;
namespace Com.Settinghead.Wexpression.Client.Controller.Template
{

    public class LoadTemplateCommand : SimpleCommand
    {
        public void execute(INotification note)
        {
            String templateId = (String) note.getBody();
            WebClient client = new WebClient();
            Uri templateUri = new Uri("/template/" + templateId + "/get", UriKind.Relative);
            client.OpenReadCompleted += Result;

            client.OpenReadAsync(templateUri);
        }

        public void Result(Object sender, OpenReadCompletedEventArgs e)
        {
            Stream s = e.Result;
            TemplateVO template = new TemplateVO(s);
            
            Facade.RetrieveProxy(TemplateProxy.NAME).SetData(template);
            SendNotification(ApplicationFacade.TEMPLATE_LOADED);
        }

        public void Fault(Object info)
        {
            CursorManager.RemoveBusyCursor();
            Alert.Show("Error: " + info.ToString());
        }
    }

}
