// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client;
using Com.Settinghead.Wexpression.Client.Model;
using Com.Settinghead.Wexpression.Client.Model.Vo.Template;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using PureMVC.Interfaces;
using PureMVC.Patterns;

namespace Com.Settinghead.Wexpression.Client.Controller.Template
{
    public class SaveTemplateCommand : SimpleCommand, IResponder
    {
        public void execute(INotification note)
        {
            TemplateVO template = note.getBody() as TemplateVO;
            if (template == null) template = templateProxy.template;

            TemplateProxy templateProxy = (facade.retrieveProxy(TemplateProxy.NAME) as TemplateProxy);

            FileReference fr = new FileReference();
            fr.save(templateProxy.toFile(template), "template.zip");
            sendNotification(ApplicationFacade.TEMPLATE_SAVED);

        }

        public void Result(Object data)
        {
        }

        public void Fault(Object info)
        {
            CursorManager.RemoveBusyCursor();
            Alert.Show("Error: " + info.ToString());
        }
    }
}
