// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client.Model;
using Com.Settinghead.Wexpression.Client.Model.Vo.Template;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using PureMVC.Interfaces;
using PureMVC.Patterns;

namespace Com.Settinghead.Wexpression.Client.Controller.Template
{
    public class UploadTemplateCommand : SimpleCommand, IResponder
    {
        private TemplateProxy templateProxy;
        public void execute(INotification note)
        {
            TemplateVO template = note.getBody() as TemplateVO;
            templateProxy = Facade.retrieveProxy(TemplateProxy.NAME) as TemplateProxy;

            templateProxy.template = template;


            //			if(template.previewPNG==null){
            //				sendNotification(ApplicationFacade.GENERATE_TEMPLATE_PREVIEW, this);
            //			}
            //			else{
            result(null);
            //			}
        }

        public void Result(Object data)
        {
            templateProxy.UploadTemplate();

        }

        public void Fault(Object info)
        {
            CursorManager.RemoveBusyCursor();
            Alert.Show("Error: " + info.ToString());
        }
    }

}
