// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Math
{
    public class MathUtils
    {
        public MathUtils()
        {
        }

        public static double Lerp(double start, double stop, double amt)
        {
            return start + (stop - start) * amt;
        }

        public static double Norm(double value_ren, double start, double stop)
        {
            return (value_ren - start) / (stop - start);
        }

        public static double Map(double value_ren, double istart, double istop, double ostart, double ostop)
        {
            return ostart + (ostop - ostart) * ((value_ren - istart) / (istop - istart));
        }

    }

}
