default:
  host: localhost
  port: 6379
development:
  db: 0
  
#  namespace: wenwentu_dev
test:
  db: 1
#  namespace: wenwentu_test

production:
#  host: herring.redistogo.com
#  port: 9908
#  password: f2b8629f3024c28a1768d4a661786397
 db:  2 
#  namespace: wenwentu_prod