// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client.Model;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using PureMVC.Interfaces;
using PureMVC.Patterns;

namespace Com.Settinghead.Wexpression.Client.Controller.Main
{
    public class PrepModelCommand : SimpleCommand
    {
        public void execute(INotification note)
        {
            // Create Template Proxy, 
            TemplateProxy templateProxy = new TemplateProxy();
            TuProxy tuProxy = new TuProxy();
            ShopProxy shopProxy = new ShopProxy();
            WordListProxy wordListProxy = new WordListProxy();

            // register it
            Facade.registerProxy(templateProxy);
            Facade.registerProxy(tuProxy);
            Facade.registerProxy(shopProxy);
            Facade.registerProxy(wordListProxy);
        }
    }
}
