// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client.View;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using PureMVC.Interfaces;
using PureMVC.Patterns;

namespace Com.Settinghead.Wexpression.Client.Controller.Main
{


    public class PrepViewCommand : SimpleCommand
    {
        /// <summary>
        /// Prepare the View.
        /// Get the View Components for the Mediators from the app,
        /// a reference to which was passed on the original startup 
        /// notification.
        /// </summary>
        ///
        public void execute(INotification note)
        {
            WexpressionClient app = WexpressionClient(note.GetBody());
            facade.RegisterMediator(new TemplateEditorMediator(app.applicationComponent.templateEditor));
            facade.RegisterMediator(new TuMediator(app.applicationComponent.tuRenderer));
            facade.RegisterMediator(new ShopMediator(app.applicationComponent.shopItemList));
            facade.RegisterMediator(new ApplicationMediator(app.applicationComponent));
        }
    }
}
