// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client.Model;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using PureMVC.Interfaces;
using PureMVC.Patterns;

namespace com.settinghead.wexpression.client.controller.main
{
    public class PrepSampleTUCommand : SimpleCommand
    {

        public PrepSampleTUCommand()
            : base()
        {
        }

        public void execute(INotification note)
        {
            TemplateProxy templateProxy = facade.retrieveProxy(TemplateProxy.NAME) as TemplateProxy;

            Array templates = new Array(
                //				"resources/templates/egg.png",
                ////				"resources/templates/egg_small.png"
                ////				,
                //				"resources/templates/face.png"
                //				,
                //				"resources/templates/wheel_h.png",
                //				"resources/templates/wheel_v.png",
                //				"resources/templates/dog.png",
                "resources/templates/heart.png"
                //				"resources/templates/apple.png"
            );
            int randomNum = Math.floor(Math.random() * (templates.length));
            templateProxy.templatePath = templates[randomNum];

            LoadupMonitorProxy monitor = facade.retrieveProxy(LoadupMonitorProxy.NAME) as LoadupMonitorProxy;
            monitor.loadResources();
        }
    }

}
