// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Controller.Main
{

    public class StartupCommand : MacroCommand
    {
        /// <summary>
        /// Add the Subcommands to startup the PureMVC apparatus.
        /// Generally, it is best to prep the Model (mostly registering 
        /// proxies)followed by preparation of the View (mostly registering 
        /// Mediators).
        /// </summary>
        ///
        protected internal void InitializeMacroCommand()
        {
            this.AddSubCommand(PrepModelCommand);
            this.AddSubCommand(PrepViewCommand);
            this.AddSubCommand(PrepSampleTUCommand);
            this.AddSubCommand(PrepSampleShopCommand);
        }
    }
}
