source 'http://rubygems.org'

gem 'rails', '3.1.3'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'pg'
# gem 'activerecord-jdbc-adapter'
# gem 'activerecord-jdbcpostgresql-adapter'
# gem 'jdbc-postgres'
# gem 'jruby-openssl'
gem 'thin'
gem 'devise'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'fb_graph'
gem 'redis'
gem "nifty-generators", :group => :development
gem 'uuidtools'
gem 'paperclip'
gem 'sqlite3'
gem 'factory_girl_rails'
gem 'impressionist'
gem 'acts_as_votable'
gem 'newrelic_rpm'
gem 'metamagic'
gem 'friendly_id'
gem "cancan"
gem 'acts-as-taggable-on'
gem 'open-meta-tags', :require => 'open_meta_tags'
gem 'client_side_validations'
gem "dynamic_form"
gem 'meta-tags', :require => 'meta_tags'
gem "koala"
gem "rack-mount"
gem "sinatra"
gem 'rack-cache', :require => 'rack/cache'
gem 'dragonfly', '~>0.9.12'
gem "twitter-bootstrap-rails"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
 gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', '0.8.2', :require => false
end
gem "mocha", :group => :test
