// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client.Model.Vo;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Sizers
{


    public class ByWeightSizer : WordSizer
    {
        private int minSize;
        private int maxSize;

        public ByWeightSizer(int minSize_0, int maxSize_1)
        {
            this.minSize = minSize_0;
            this.maxSize = maxSize_1;

        }

        public virtual double SizeFor(WordVO word, int wordRank, int wordCount)
        {
            //			MathUtils.lerp(minSize+(maxSize-minSize)/2, maxSize, word.weight) 

            return maxSize - Math.Pow(Math.Sqrt((maxSize - minSize)) * wordRank / wordCount, 2);
        }
    }

}
