// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client;
using Com.Settinghead.Wexpression.Client.Angler;
using Com.Settinghead.Wexpression.Client.Density;
using Com.Settinghead.Wexpression.Client.Model.Vo;

using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using System.Windows;

namespace Com.Settinghead.Wexpression.Client.Nudger
{

    /*
     Copyright 2010 Daniel Bernier
	
     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at
	
     http://www.apache.org/licenses/LICENSE-2.0
	
     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
     */

    public class ShapeConfinedSpiralWordNudger : WordNudger
    {

        // Who knows? this seems to be good, but it seems to depend on the font --
        // bigger fonts need a bigger thetaIncrement.
        //	private double thetaIncrement= Math.PI * 0.03;
        private WordAngler angler;

        public ShapeConfinedSpiralWordNudger()
        {
            this.retPoint = new Point(0, 0);
        }
        private Point retPoint;

        public virtual Point NudgeFor(WordVO w, PlaceInfo pInfo, int attempt, int totalPlannedAttempt)
        {
            int factor;
            attempt = (attempt + pInfo.patch.lastAttempt) % totalPlannedAttempt;

            //		if (pInfo != null && pInfo.get().patch != null) {
            Patch p = Patch(pInfo.patch);
            factor = (p.GetWidth() < p.GetHeight()) ? p.GetWidth() : p
                    .GetHeight();
            factor /= 1.8d;
            //			if (p.getLevel() == 0)
            //				factor /= 6;
            //			else if (p.getLevel() == 1)
            //				factor /= 2;
            //		} else
            //			factor = 30;

            //		factor *= 6;

            double rad = PowerMap(0.6d, attempt, 0, totalPlannedAttempt, 1, factor);

            //		var thetaIncrement = powerMap(1, attempt, 0, totalPlannedAttempt, 0.5, 0.3);
            //		double theta= thetaIncrement * attempt;
            double theta = (new Random()).Next() * BBPolarTreeVO.TWO_PI;
            double x = System.Math.Cos(theta) * rad;
            double y = System.Math.Sin(theta) * rad;
            retPoint.x = x;
            retPoint.y = y;
            return retPoint;
        }

        private double PowerMap(double power, double v, double min1, double max1, double min2, double max2)
        {
            double val = Com.Settinghead.Wexpression.Client.Math.MathUtils.Norm(v, min1, max1);
            val = Math.Pow(val, power);
            return Com.Settinghead.Wexpression.Client.Math.MathUtils.Lerp(min2, max2, val);
        }
    }


}
