// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Angler
{
    public class MostlyHorizAngler : PickFromAngler
    {
        public MostlyHorizAngler()
        {
            super(new double[]{0, 0, 0, 0, 0
				//	, BBPolarTreeVO.HALF_PI,-BBPolarTreeVO.HALF_PI
				});
            //			super(Vector.<double>([0.3,-0.3]));
        }
    }

}
