// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client.Model.Vo;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;

namespace Com.Settinghead.Wexpression.Client.Angler
{

    public class PickFromAngler : WordAngler
    {

        private IList<double> angles;
        private Random rnd = new Random();
        public PickFromAngler(IList<double> angles)
        {
            this.angles = angles;
        }

        public virtual double AngleFor(EngineWordVO eWord)
        {
            return angles[rnd.Next(angles.Count)];
        }
    }

}
