// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client.Model.Vo;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Fonter
{

    public class AlwaysUseFonter : WordFonter
    {

        private String fontName;
        public AlwaysUseFonter(String fontName_0)
        {
            this.fontName = fontName_0;
        }

        public virtual String FontFor(WordVO word)
        {
            return fontName;
        }
    }

}
