// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using PureMVC.Patterns;
using Com.Settinghead.Wexpression.Client.Controller;
using Com.Settinghead.Wexpression.Client.Controller.Template;
using Com.Settinghead.Wexpression.Client.Controller.Tu;
namespace Com.Settinghead.Wexpression.Client
{
    public class ApplicationFacade : Facade
    {
        #region Constants
        public const string STARTUP = "startup";
        public const string RENDER_TU = "renderTu";
        public const string TU_GENERATED = "tuGenerated";
        public const string EDIT_TEMPLATE = "editTemplate";
        public const string GENERATE_TU = "generateTu";
        public const string DISPLAYWORD_CREATED = "displaywordCreated";
        public const string TEMPLATE_EDIT_MOUSE_DOWN = "templateEditMouseDown";
        public const string WORD_LIST_LOADED = "wordListLoaded";
        public const string TEMPLATE_LOADED = "templateLoaded";
        public const string LOAD_TEMPLATE = "loadTemplate";
        public const string TEMPLATE_SAVED = "templateSaved";
        public const string TEMPLATE_UPLOADED = "templateUploaded";
        public const string SAVE_TEMPLATE = "saveTemplate";
        public const string UPLOAD_TEMPLATE = "uploadTemplate";
        public const string GENERATE_TEMPLATE_PREVIEW = "generateTemplatePreview";
        public const string TEMPLATE_PREVIEW_GENERATED = "templatePreviewGenerated";
        public const string TU_GENERATION_LAST_CALL = "tuGenerationLastCall";
        #endregion


        /// <summary>
        /// Start the application
        /// </summary>
        ///
        public void Startup(object app)
        {
            SendNotification(STARTUP, app);
        }

        /// <summary>
        /// Register Commands with the Controller 
        /// </summary>
        ///
        protected internal void InitializeController()
        {
            base.InitializeController();
            RegisterCommand(STARTUP, StartupCommand);
            RegisterCommand(LOAD_TEMPLATE, LoadTemplateCommand);
            RegisterCommand(SAVE_TEMPLATE, SaveTemplateCommand);
            RegisterCommand(UPLOAD_TEMPLATE, UploadTemplateCommand);
            RegisterCommand(GENERATE_TEMPLATE_PREVIEW, GenerateTemplatePreviewCommand);
            RegisterCommand(GENERATE_TU, GenerateTuCommand);
        }

        /// <summary>
        /// Singleton Factory Method
        /// </summary>
        ///
        public static ApplicationFacade getInstance()
        {
            if (Instance == null) Instance = new ApplicationFacade();
            return (ApplicationFacade)Instance;
        }
    }

}
