// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client.Density;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using System.Windows;
namespace Com.Settinghead.Wexpression.Client
{


    public class PlaceInfo
    {
        private Point pVector;
        private Patch _patch;

        public PlaceInfo(Point pVector_0, Patch p = null)
        {
            this.setpVector(pVector);
            this.patch = p;
        }


        private void SetpVector(Point pVector_0)
        {
            this.pVector = pVector_0;
        }

        public Point GetpVector()
        {
            return pVector;
        }

        public Patch Patch
        {
            set
            {
                this._patch = value;
            }
            get
            {
                return this._patch;
            }
        }

        public PlaceInfo Get()
        {
            return new PlaceInfo(new Point(this.GetpVector().X, this.GetpVector().Y), this.Patch);
        }

        public double DistanceFrom(PlaceInfo p)
        {
            return Math.Sqrt(Math.Pow(p.GetpVector().X - this.GetpVector().X, 2) +
                            Math.Pow(p.GetpVector().Y - this.GetpVector().Y, 2));
        }
    }

}
