// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client
{

    public class RenderOptions
    {
        public RenderOptions()
        {
            this.maxAttemptsToPlaceWord = -1;
            this.maxdoubleOfWordsToDraw = -1;
            this.minShapeSize = 10;
            this.wordPadding = 0;
        }
        public int maxAttemptsToPlaceWord; // default: based on Word weight
        public int maxdoubleOfWordsToDraw; // default: unlimited
        public int minShapeSize;
        public int wordPadding;
    }

}
