// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Density
{

    public class LeveledPatchMap
    {

        private IList<PatchQueue> _map = new List<PatchQueue>();
        private DensityPatchIndex _index;

        public LeveledPatchMap(DensityPatchIndex index)
        {
            this._index = index;
            //top level map
            //			PatchQueue topLevelQueue= new PatchQueue(0, this);
            //			this._map.push(topLevelQueue);

        }


        public Patch GetBestPatchAtLevel(int level)
        {
            PatchQueue queue = GetQueue(level);
            return queue.GetBestPatch();
        }

        public PatchQueue GetQueue(int level)
        {
            if (level >= _map.length)
                GenerateLevelQueue(level);
            return _map[level];

        }

        private void GenerateLevelQueue(int level)
        {
            if (level == 0)
            {
                PatchQueue topLevelQueue = new PatchQueue(0, this);
                this._map.Push(topLevelQueue);
            }
            else
            {
                if (level > _map.length)
                    GenerateLevelQueue(level - 1);
                _map.Push((_map[_map.length - 1].Descend(level)));
            }

        }

        public DensityPatchIndex GetIndex()
        {
            return this._index;
        }

        public void Add(Patch patch)
        {
            GetQueue(patch.GetLevel()).TryAdd(patch);
        }

    }

}
