// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Density
{

    public class PatchComparator : IComparator<Patch>
    {

        public NumericComparator _numComparator;
        public PatchComparator(String order = NumericComparator.ORDER_DESC)
        {
            _numComparator = new NumericComparator(order);
        }

        public int Compare(Patch item1, Patch item2)
        {
            if (!(item1 is Patch)) throw new UncomparableType(String, item1);
            if (!(item2 is Patch)) throw new UncomparableType(String, item2);

            Patch p1 = item1;
            Patch p2 = item2;

            //			int r= -_numComparator.compare(p1.getAverageAlpha(),p2.getAverageAlpha());
            int r = -_numComparator.compare(p1.numberOfFailures, p2.numberOfFailures);

            if (r == 0)
            {
                r = _numComparator.compare(p1.getAlphaSum(), p2.getAlphaSum());
                if (r == 0)
                    return p1.getRank() - p2.getRank();
                else
                    return r;
            }
            else return r;
        }
    }

}
