// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client.Model;
using Com.Settinghead.Wexpression.Client.Model.Vo;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using PureMVC.Patterns;
using PureMVC.Interfaces;
namespace Com.Settinghead.Wexpression.Client.Controller.Tu
{


    public class GenerateTuCommand : SimpleCommand
    {
        public void execute(INotification note)
        {
            TuVO tu = note.getBody() as TuVO;
            TuProxy tuProxy = Facade.retrieveProxy(TuProxy.NAME) as TuProxy;
            if (tu == null)
                tu = tuProxy.tu;
            tuProxy.template = tu.template;
            tuProxy.wordList = tu.words;
            tuProxy.load();
        }
    }
}
