// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client;
using Com.Settinghead.Wexpression.Client.Model;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using Com.Settinghead.Wexpression.Client.View.Components;
using PureMVC.Interfaces;
using PureMVC.Patterns; 
namespace Com.Settinghead.Wexpression.Client.View
{

    public class ShopMediator : Mediator
    {
        private ShopProxy shopProxy;
        new public const string NAME = "ShopMediator";

        public ShopMediator(Object viewComponent)
            : base(NAME, viewComponent)
        {
            
        }

        private ShopItemList shopItemList
        {
            get
            {
                return (ShopItemList)ViewComponent;
            }
        }

        public void OnRegister()
        {
            shopProxy = Facade.retrieveProxy(ShopProxy.NAME) as ShopProxy;
        }

        public override IList<String> ListNotificationInterests()
        {
            return new List<string>{
					ApplicationFacade.TU_GENERATED};
        }

        public void handleNotification(INotification note)
        {
            switch (note.getName())
            {
                case ApplicationFacade.TU_GENERATED:
                    shopItemList.img = (note.getBody() as TuVO).generatedImage;
                    shopItemList.list = shopProxy.shop;
                    break;
            }
        }
    }


}
