// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client;
using Com.Settinghead.Wexpression.Client.Model;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
namespace Com.Settinghead.Wexpression.Client.View
{

    public class ShopMediator : Mediator
    {
        private ShopProxy shopProxy;
        public static const string NAME = "ShopMediator";

        public ShopMediator(Object viewComponent)
        {
            super(NAME, viewComponent);
        }

        private ShopItemList shopItemList
        {
            get
            {
                return (ShopItemList)viewComponent;
            }
        }

        public void OnRegister()
        {
            shopProxy = facade.retrieveProxy(ShopProxy.NAME) as ShopProxy;
        }

        public override IList<String> listNotificationInterests()
        {
            return new List<string>{
					ApplicationFacade.TU_GENERATED};
        }

        public void handleNotification(INotification note)
        {
            switch (note.getName())
            {
                case ApplicationFacade.TU_GENERATED:
                    shopItemList.img = (note.getBody() as TuVO).generatedImage;
                    shopItemList.list = shopProxy.shop;
                    break;
            }
        }
    }


}
