// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.Windows.Controls;
using System.IO;
using System.Runtime.CompilerServices;
namespace com.settinghead.wexpression.client.model.vo
{


    public class DisplayWordVO : UserControl
    {
        private EngineWordVO _engineWord;

        public DisplayWordVO(EngineWordVO eWord)
            : base()
        {
            this._engineWord = eWord;
        }

        public EngineWordVO engineWord()
        {
            return this._engineWord;
        }
    }

}
