// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Model.Vo
{
    public interface IImageShape
    {
        bool Contains(int x, int y, int width, int height, double rotation, bool transformed);
        bool ContainsPoint(int x, int y, bool transformed);
        //bool Intersects(double x, double y, double width, double height, bool transformed);

        double Width { get; }
        double Height { get; }
    }
}
