// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Model.Vo
{
    public interface IZipOutput
    {
        void PutStringToFile(String fileName, String data); void putBytesToFile(String fileName, ByteArray bytes); void putBitmapDataToPNGFile(String fileName, BitmapData bmpData); void Process(Object obj0, String dirName = null);
    }

}
