// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using System.Windows.Media.Imaging;
namespace Com.Settinghead.Wexpression.Client.Model.Vo
{
    public class ShopItemVO
    {
        private WriteableBitmap _img;
        private WriteableBitmap _thumb;
        private String _item_url;

        public ShopItemVO(String url)
        {
            this._item_url = url;
        }

        public WriteableBitmap image
        {
            get
            {
                return _img;
            }
            set
            {
                this._img = value;
            }
        }

        public WriteableBitmap thumbnail
        {
            get
            {
                return _thumb;
            }
            set
            {
                this._thumb = value;
            }
        }

        public string itemUrl
        {
            get
            {
                return _item_url;
            }
            set
            {
                this._item_url = value;

            }
        }
    }
}
