// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Model.Vo
{
    public class WordListVO : SortedList
    {
        public WordListVO(Array array = null)
        {
            super(new WordComparator());
            if (array != null)
            {
                for (int i = 0; i < array.length; i++)
                {
                    this.add(new WordVO(array[i].word, array[i].weight));
                }
            }
        }
    }
}
