// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:00 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using Wintellect.PowerCollections;
namespace Com.Settinghead.Wexpression.Client.Model.Vo
{
    public class WordListVO : OrderedBag<WordVO>
    {
        public WordListVO(List<WordVO> array = null):base()
        {
            if (array != null)
            {
                for (int i = 0; i < array.length; i++)
                {
                    this.Add(new WordVO(array[i].word, array[i].weight));
                }
            }
        }
    }
}
