// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Model.Vo
{
    public class WordVO:IComparable<WordVO>
    {
        public String word;
        public double weight;

        public WordVO(String word, double weight)
        {
            this.word = word;
            this.weight = weight;
        }

        public int CompareTo(WordVO w)
        {
            return this.weight.CompareTo(w.weight);
        }
    }

}
