// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
using Com.Settinghead.Wexpression.Client.Model.Vo;
namespace Com.Settinghead.Wexpression.Client.Model
{

    public class ShopProxy : EntityProxy
    {
        new public const string NAME = "ShopProxy";
        new public const string SRNAME = "ShopSRProxy";

        public ShopProxy():base(NAME, new List<ShopItemVO>())
        {
        }

        // return data property cast to proper type
        public IList<ShopItemVO>  Shop
        {
            get
            {
                return (IList<ShopItemVO>)data;
            }
        }

        // add an item to the data
        public void AddItem(ShopItemVO item)
        {
            Shop.Add(item);
        }
    }
}
