// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Model
{

    public class ShopProxy : EntityProxy, ILoadupProxy
    {
        public static const string NAME = "ShopProxy";
        public static const string SRNAME = "ShopSRProxy";

        public ShopProxy()
        {
            super(NAME, new ArrayCollection());
        }

        public void Load()
        {
        }

        // return data property cast to proper type
        public ArrayCollection shop
        {
            get
            {
                return (ArrayCollection)data;
            }
        }

        // add an item to the data
        public void AddItem(Object item)
        {
            shop.AddItem(item);
        }
    }
}
