// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client.Model.Vo;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Model
{

    public class WordListProxy : EntityProxy, ILoadupProxy
    {
        public static const string NAME = "WordListProxy";
        public static const string SRNAME = "WordListSRProxy";

        private WordListVO _list = null;

        public WordListProxy()
        {
            super(NAME, null);
        }

        private URLLoader loader;
        public void Load()
        {
            if (this._list == null)
            {

                String wordListId = FlexGlobals.topLevelApplication.parameters.wordListId;
                URLRequest request = new URLRequest("wordlists/" + wordListId);
                URLVariables urlVariables = new URLVariables();
                request.data = urlVariables;
                request.method = URLRequestMethod.GET;
                loader = new URLLoader();
                loader.addEventListener(Event.COMPLETE, jsonLoaded);
                loader.load(request);

            }
        }

        public void jsonLoaded(Event e)
        {

            Array l = (new JSONDecoder(loader.data, false).getValue() as Object).list;
            WordListVO wordList = new WordListVO(l);
            this._list = wordList;
        }


        public WordListVO currentWordList
        {
            get
            {
                return _list;
            }
        }

        public WordListVO SampleWordList()
        {
            WordListVO list = new WordListVO();
            for (int i = 0; i < 1000; i++)
            {
                list.Add(new WordVO("Art", (new Random()).Next() * 5 + 0.5d));
                list.Add(new WordVO("Sample", (new Random()).Next() * 5 + 0.5d));
                list.Add(new WordVO("Created by Wexpression", (new Random()).Next() * 5 + 0.5d));
                list.Add(new WordVO("typography", (new Random()).Next() * 5 + 0.5d));
            }
            return list;
        }
    }
}
