struct SlapInfo;
void initCanvas();
void setPerseverance(int perseverance);
void feedShape(unsigned int *pixels, int width, int height, unsigned int sid);
int getStatus();
void setStatus(int status);
double getShrinkage();
void appendLayer(unsigned int *pixels, unsigned int *colorPixels, int width, int height,bool flip);
void updateTemplate(unsigned int *data);
void feedShape(unsigned int *data);
void startRendering();
void pauseRendering();
SlapInfo* getNextSlap();
SlapInfo* tryNextShape();
SlapInfo* slapShape(unsigned int *pixels, int width, int height,unsigned int sid);
unsigned int getNumberOfPendingShapes();