// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 3/28/12 3:01 AM    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
using Com.Settinghead.Wexpression.Client;
using Com.Settinghead.Wexpression.Client.Density;
using Com.Settinghead.Wexpression.Client.Model.Vo;
using Com.Settinghead.Wexpression.Client.Model.Vo.Template;
using System;
using System.Collections;
using System.ComponentModel;
using System.IO;
using System.Runtime.CompilerServices;
namespace Com.Settinghead.Wexpression.Client.Placer
{



    public class ShapeConfinedPlacer : WordPlacer
    {

        private TemplateVO img;
        private DensityPatchIndex index;

        public ShapeConfinedPlacer(TemplateVO img_0, DensityPatchIndex index_1)
        {
            this.SetImg(img_0);
            this.SetIndex(index_1);
        }

        public virtual ArrayList<PlaceInfo> Place(WordVO word, int wordIndex, int wordsCount, int wordImageWidth, int wordImageHeight, int fieldWidth, int fieldHeight)
        {


            ArrayList<Patch> patches = indPatchFor(wordImageWidth,
                    wordImageHeight);

            index.Lock();
            IList<PlaceInfo> places = new List<PlaceInfo>();
            for (int i = 0; i < patches.length; i++)
                places.push(new PlaceInfo(new Po((int)(patches[i] as Patch).getX() + (patches[i] as Patch).getWidth() / 2, (patches[i] as Patch).getY()
                + (patches[i] as Patch).getHeight() / 2), (patches[i] as Patch)));
            return places;
        }

        private void SetImg(TemplateVO img_0)
        {
            this.img = img_0;
        }

        public TemplateVO GetImg()
        {
            return img;
        }

        public void SetIndex(DensityPatchIndex index_0)
        {
            this.index = index_0;
        }

        public DensityPatchIndex GetIndex()
        {
            return index;
        }


        public virtual void Fail(Object returnedObj)
        {

            foreach (PlaceInfo pi in ((IList<PlaceInfo>)returnedObj))
            {
                index.add(pi.patch);
            }

            index.unlock();
        }


        public virtual void Success(Object returnedObj)
        {
            foreach (PlaceInfo pi in ((IList<PlaceInfo>)returnedObj))
            {
                index.add(pi.patch);
            }

            index.unlock();
        }

    }

}
