/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2012-04-23 18:56:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.templates;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.UUID;
import java.util.Random;

public final class show_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

UUID swfRandomizer = UUID.randomUUID();

      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t// For version detection, set to min. required Flash Player version, or 0 (or 0.0.0), for no version detection. \n");
      out.write("\tvar swfVersionStr = \"10.2.0\";\n");
      out.write("\t// To use express install, set to playerProductInstall.swf, otherwise the empty string. \n");
      out.write("\tvar xiSwfUrlStr = \"playerProductInstall.swf\";\n");
      out.write("\tvar flashvars = {};\n");
      out.write("\tflashvars.templateId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${templateId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\n");
      out.write("\tflashvars.mode = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\n");
      out.write("\tvar params = {};\n");
      out.write("\tparams.quality = \"high\";\n");
      out.write("\tparams.bgcolor = \"#ffffff\";\n");
      out.write("\tparams.allowscriptaccess = \"sameDomain\";\n");
      out.write("\tparams.allowfullscreen = \"true\";\n");
      out.write("\tvar attributes = {};\n");
      out.write("\tattributes.id = \"Main\";\n");
      out.write("\tattributes.name = \"Main\";\n");
      out.write("\tattributes.align = \"middle\";\n");
      out.write("\tswfobject.embedSWF(\n");
      out.write("\t\t\t\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" + \"?rnd=");
      out.print(swfRandomizer);
      out.write("\",\n");
      out.write("\t\t\t\"flashContent\", \"100%\", \"100%\", swfVersionStr, xiSwfUrlStr,\n");
      out.write("\t\t\tflashvars, params, attributes);\n");
      out.write("\t// JavaScript enabled so display the flashContent div in case it is not replaced with a swf object.\n");
      out.write("\tswfobject.createCSS(\"#flashContent\", \"display:block;text-align:left;\");\n");
      out.write("</script>\n");
      out.write("<!-- SWFObject's dynamic embed method replaces this alternative HTML content with Flash content when enough \n");
      out.write("             JavaScript and Flash plug-in support is available. The div is initially hidden so that it doesn't show\n");
      out.write("             when JavaScript is disabled.\n");
      out.write("        -->\n");
      out.write("<div id=\"flashContent\">\n");
      out.write("\t<p>To view this page ensure that Adobe Flash Player version 10.2.0\n");
      out.write("\t\tor greater is installed.</p>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\tvar pageHost = ((document.location.protocol == \"https:\") ? \"https://\"\n");
      out.write("\t\t\t\t: \"http://\");\n");
      out.write("\t\tdocument\n");
      out.write("\t\t\t\t.write(\"<a href='http://www.adobe.com/go/getflashplayer'><img src='\" \n");
      out.write("                                + pageHost + \"www.adobe.com/images/shared/download_buttons/get_flash_player.gif' alt='Get Adobe Flash player' /></a>\");\n");
      out.write("\t</script>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<noscript>\n");
      out.write("\t<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\"\n");
      out.write("\t\twidth=\"100%\" height=\"100%\" id=\"Main\" name=\"Main\">\n");
      out.write("\t\t<param name=\"movie\"\n");
      out.write("\t\t\tvalue=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("?rnd=");
      out.print(swfRandomizer);
      out.write("\" />\n");
      out.write("\t\t<param name=\"quality\" value=\"high\" />\n");
      out.write("\t\t<param name=\"bgcolor\" value=\"#ffffff\" />\n");
      out.write("\t\t<param name=\"allowScriptAccess\" value=\"sameDomain\" />\n");
      out.write("\t\t<param name=\"allowFullScreen\" value=\"true\" />\n");
      out.write("\t\t<param name=\"FlashVars\"\n");
      out.write("\t\t\tvalue=\"mode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&templateId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${templateId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\n");
      out.write("\t\t<!--[if !IE]>-->\n");
      out.write("\t\t<object type=\"application/x-shockwave-flash\"\n");
      out.write("\t\t\tdata=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("?rnd=");
      out.print(swfRandomizer);
      out.write("\"\n");
      out.write("\t\t\twidth=\"100%\" height=\"100%\">\n");
      out.write("\t\t\t<param name=\"quality\" value=\"high\" />\n");
      out.write("\t\t\t<param name=\"bgcolor\" value=\"#ffffff\" />\n");
      out.write("\t\t\t<param name=\"allowScriptAccess\" value=\"sameDomain\" />\n");
      out.write("\t\t\t<param name=\"allowFullScreen\" value=\"true\" />\n");
      out.write("\t\t\t<param name=\"FlashVars\"\n");
      out.write("\t\t\t\tvalue=\"mode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&templateId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${templateId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\n");
      out.write("\t\t\t<!--<![endif]-->\n");
      out.write("\t\t\t<!--[if gte IE 6]>-->\n");
      out.write("\t\t\t<p>Either scripts and active content are not permitted to run or\n");
      out.write("\t\t\t\tAdobe Flash Player version 10.2.0 or greater is not installed.</p>\n");
      out.write("\t\t\t<!--<![endif]-->\n");
      out.write("\t\t\t<a href=\"http://www.adobe.com/go/getflashplayer\"> <img\n");
      out.write("\t\t\t\tsrc=\"http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif\"\n");
      out.write("\t\t\t\talt=\"Get Adobe Flash Player\" />\n");
      out.write("\t\t\t</a>\n");
      out.write("\t\t\t<!--[if !IE]>-->\n");
      out.write("\t\t</object>\n");
      out.write("\t\t<!--<![endif]-->\n");
      out.write("\t</object>\n");
      out.write("</noscript>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/templates/show.jsp(29,4) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/resources/flash/WexpressionClient.swf");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/views/templates/show.jsp(55,10) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/resources/flash/WexpressionClient.swf");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/views/templates/show.jsp(64,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("resources/flash/WexpressionClient.swf");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }
}
